import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import faceRegonition from "../../Assets/Projects/smartbrain.png";
import Robofriends from "../../Assets/Projects/robofriends.png";
import summerActivities from "../../Assets/Projects/summer.png";
import English4Kids from "../../Assets/Projects/english4kids.jpg"; 
import zeroRobotics from "../../Assets/Projects/zerorobotics.gif"; 

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={faceRegonition}
              isBlog={false}
              title="Face recognition"
              description="Face recognition represent a web application where a user can log in and type a photo address for a face recognition.
              All valid links which were scanned will represent an entry count which will be displayed. Also, a user can register with new data.
              This web app use Clarifai API for face detection and Render for an online deploying."
              ghLink="https://github.com/TeodoraMM/face-regonition-frontend"
              demoLink="https://face-regonition.onrender.com"
            />
          </Col>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={Robofriends}
              isBlog={false}
              title="Robofriends"
              description="RoboFreinds represents a web application where we can filter robots by their name.
              Every robot's picture is randomly generated by https://robohash.org/ and included in 
              the application along with a name. Not least, the page is also responsive.
              Developing this web application, I learned the first steps in React and deploying."
              ghLink="https://github.com/TeodoraMM/robofriends"
              demoLink="https://robofriends-q9hj.onrender.com/"
            />
          </Col>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={summerActivities}
              isBlog={false}
              title="Summer Activities"
              description="Summer Activities is a Java application developed in InteliJ IDEA.
              In this app the data can be read and write in a file and displayed on the interface where the user can also add, delete or update a summer activity.
              Also, a user can enroll for a summer activity by filtering it by name and add a registration if he or she is in the right interval of age ."
              ghLink="https://github.com/TeodoraMM/SummerActivities"
            />
          </Col>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={English4Kids}
              isBlog={false}
              title="English4Kids"
              description=" English4Kids represents an educational software for the childrens between age 8 and 12 designed to help them to learn english while playing.The software includes a base game where childrens can go around the house and click on objects an try to guess their nameing in english and if they guess correct than they collect points. Others game included are the hangman, dress the boy/girl, cooking a recipe and a dictionary where they can search and add words."
              ghLink="https://github.com/TeodoraMM/English4Kids"
            />
          </Col>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={zeroRobotics}
              isBlog={false}
              title="Zero Robotics"
              description="Zero Robotics is an international high school programming competition where students control robotic SPHERES (Synchronised Position Hold Engage and Reorient Experimental Satellites) aboard the International Space Station. Each year teams of students work to produce code capable of performing in a game that can be deployed on the SPHERES. This game generally contains elements such as docking with objects, moving objects, and destroying targets within a bounded area while monitoring fuel usage.
              "
            />
          </Col>
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
